language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
script:
  - ./gradlew :pact-jvm-consumer-kotlin:asciidoctor --no-daemon
install: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: pact-jvm-consumer-kotlin/build/asciidoc
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^trigger-travis.*$
