= kPact - Kotlin idiomatic DSL for Pact
:p: icon:check[role="green"]
:n: icon:times[role="red"]
:exampleDir: ../src/test/kotlin/au/com/dius/pact/consumer/kotlin/dsl/examples

== Goals
* the resulting Pact should be good readable
* writing the Pact should be as simple as possible
* Compile time safety (e.g. force mandatory data to be set)
* short and concise syntax (no boilerplate)
* IDE support (e.g. auto-completion)
* Things belonging to each other are in the same block
* Things on the same logical level are on the same indentation level (auto-indentation of IDE)
* Usable also from https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit5[pact-jvm-consumer-junit5]
  (from `PactDslWithProvider` to `RequestResponsePact`)
* Support both:
  1. prose like infix syntax (e.g. `"consumer" and "provider" havePact`)
  2. fluent interface syntax (e.g. `consumer("consumer").hasPactWith("provider")`)

== Examples

[source,java,indent=0,role="primary"]
.Infix DSL
----
include::{exampleDir}/InfixDslExample.kt[tags=infixDSL]
----

[source,java,indent=0,role="secondary"]
.Fluent DSL
----
include::{exampleDir}/FluentDslExample.kt[tags=fluentDSL]

----

[source,java,indent=0,role="secondary"]
.ConsumerPactBuilder
----
include::{exampleDir}/ConsumerPactBuilderExample.kt[tags=ConsumerPactBuilder]
----

== Usage together with https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit5[pact-jvm-consumer-junit5]

[source,java,indent=0,role="primary"]
.kPact
----
include::{exampleDir}/Junit5Example.kt[tags=kPact]
----

[source,java,indent=0,role="secondary"]
.ConsumerPactBuilder
----
include::{exampleDir}/Junit5Example.kt[tags=ConsumerPactBuilder]
----

== Open Design Decisions

=== infix: Prose or CamelCase

The open design decisions are the code callouts 2-5 in the following code:

[source,java,indent=0,role="primary"]
.CamelCase
----
include::{exampleDir}/DesignDecisions.kt[tags=CamelCase]
----
<1> `and1` will be named just `and` but before the decision is made, this would lead to a name collision
<2> `isDefinedBy` could be `defined by` or removed completely
<3> `then` could be removed
<4> `and` could be removed
<5> `thenRespondWith` could be split into `then respond with`

[source,java,indent=0,role="secondary"]
.like prose
----
include::{exampleDir}/DesignDecisions.kt[tags=proseLike]
----
<1> `and1` will be named just `and` but before the decision is made, this would lead to a name collision
<2> `isDefinedBy` could be `defined by` or removed completely
<3> `then` could be removed
<4> `and` could be removed
<5> `thenRespondWith` could be split into `then respond with`

[source,java,indent=0,role="secondary"]
.like prose shorter
----
include::{exampleDir}/DesignDecisions.kt[tags=proseLikeShorter]
----
<1> `and1` will be named just `and` but before the decision is made, this would lead to a name collision
<2> `isDefinedBy` could be `defined by` or removed completely
<3> `then` could be removed
<4> `and` could be removed
<5> `thenRespondWith` could be split into `then respond with`

Please comment on the https://github.com/usr42/pact-jvm/pull/3/files#diff-faecfe8d688a94b5a23fe936b9394f11[DesignDecisions.kt of the RFC PR]