= kPact - Kotlin idiomatic DSL for Pact
:p: icon:check[role="green"]
:n: icon:times[role="red"]
:exampleDir: ../src/test/kotlin/au/com/dius/pact/consumer/kotlin/dsl/examples

== Goals
* the resulting Pact should be good readable
* writing the Pact should be as simple as possible
* Compile time safety (e.g. force mandatory data to be set)
* short and concise syntax (no boilerplate)
* IDE support (e.g. auto-completion)
* Things belonging to each other are in the same block
* Things on the same logical level are on the same indentation level (auto-indentation of IDE)
* Usable also from https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit5[pact-jvm-consumer-junit5]
  (from `PactDslWithProvider` to `RequestResponsePact`)
* Support both:
  1. prose like infix syntax (e.g. `"consumer" and "provider" havePact`)
  2. fluent interface syntax (e.g. `consumer("consumer").hasPactWith("provider")`)

== Examples

[source,java,indent=0,role="primary"]
.Infix DSL
----
include::{exampleDir}/InfixDslExample.kt[lines=11..47]
----

[source,java,indent=0,role="secondary"]
.Fluent DSL
----
include::{exampleDir}/FluentDslExample.kt[lines=11..47]

----

[source,java,indent=0,role="secondary"]
.ConsumerPactBuilder
----
include::{exampleDir}/ConsumerPactBuilderExample.kt[lines=7..43]
----

== Usage together with https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit5[pact-jvm-consumer-junit5]

[source,java,indent=0,role="primary"]
.kPact
----
include::{exampleDir}/Junit5Example.kt[lines=14..26]
----

[source,java,indent=0,role="secondary"]
.ConsumerPactBuilder
----
include::{exampleDir}/Junit5Example.kt[lines=30..41]
----

== Open Design Decisions

=== kPact block VS enforcing single Consumer/Provider pair

==== Examples

[source,java,indent=0,role="primary"]
.kpact block example
----
kPact {
    consumer withName "consumer" andProvider "provider" havePact {
        // ...
    }
}
----

[source,java,indent=0,role="secondary"]
.enforcing single Consumer/Provider pair example
----
KPact between "consumer" andProvider "provider" isDefinedBy {
    // ...
}
----

==== Comparing the different DSL styles

===== kpact block

{n}
  **compile time safety** / unexpected and inconsistent behavior: +
  Multiple consumer/provider blocks are not prevented by compiler but
  only last one would be used:
[source,java,indent=0]
----
      kPact {
          consumer withName "consumer" andProvider "provider" havePact { // <1>
              // ...
          }

          consumer withName "consumer" andProvider "provider" havePact {
              // ...
          }
      }
----
<1> This `consumer` block is not used at all


{p}
  Indicates clearer, that the block defines a (k)Pact

===== enforcing single pair

{p}
  one indentation level less

=== String extension function

==== Examples

===== without String extension

[source,java,indent=0,role="primary"]
.infix
----
consumer withName "consumer" andProvider "provider" havePact {
----

[source,java,indent=0,role="secondary"]
.fluent
----
consumer("consumer").hasPactWith("provider") {
----

===== with String extension

[source,java,indent=0,role="primary"]
.infix
----
"consumer" and "provider" havePact {
----
[source,java,indent=0,role="secondary"]
.fluent
----
"consumer".hasPactWith("provider") {
----

==== Comparing the different DSL styles

===== with extension

{p}
  shorter and more concise

{p}
  **infix syntax** is nearer to prose

===== without extension

{p}
  better IDE auto-completion

{p}
  **fluent interface** feels more natural without String extension (opinion)